gha deps:(deps): bump actions/checkout from 4.1.2 to 4.1.4 (#50)
* gha deps:(deps): bump actions/checkout from 4.1.2 to 4.1.4

Bumps [actions/checkout](https://github.com/actions/checkout) from 4.1.2 to 4.1.4.
- [Release notes](https://github.com/actions/checkout/releases)
- [Changelog](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- [Commits](https://github.com/actions/checkout/compare/9bb56186c3b09b4f86b1c65136769dd318469633...0ad4b8fadaa221de15dcec353f45205ec38ea70b)

---
updated-dependencies:
- dependency-name: actions/checkout
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

* Add .changelog entry #50

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: dependabot[bot] <dependabot[bot]@users.noreply.github.com>

diff --git a/.github/workflows/changelog-checker.yml b/.github/workflows/changelog-checker.yml
--- a/.github/workflows/changelog-checker.yml
+++ b/.github/workflows/changelog-checker.yml
@@ -4,22 +4,88 @@ name: Changelog Entry
 
 on:
   pull_request:
-    types: [opened, synchronize, labeled]
+    types: [opened, synchronize, labeled, reopened]
     # Runs on PRs to main and all release branches
     branches:
       - main
 
+permissions:
+  pull-requests: write
+  contents: write
+
 jobs:
+  generate-release-note:
+    if: github.actor == 'dependabot[bot]'
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
+      with:
+        fetch-depth: 0
+        ref: ${{ github.event.pull_request.head.ref }}
+    - name: Generate .changelog entry
+      env:
+        PR_NUMBER: ${{ github.event.pull_request.number }}
+        PR_TITLE: ${{ github.event.pull_request.title }}
+        PR_BODY: ${{ github.event.pull_request.body_text }}
+      run: |
+        FIRST_COMMIT=$(git log -10 --pretty=format:%H origin/main..HEAD | tail -1)
+        FIRST_COMMIT_BODY=$(git log -1 --pretty=format:%B $FIRST_COMMIT)
+        mkdir -p .changelog
+        echo "backticksrelease-note:enhancement" > .changelog/$PR_NUMBER.txt
+        echo "ci/dependabot: $PR_TITLE" >> .changelog/$PR_NUMBER.txt
+        echo ""  >> .changelog/$PR_NUMBER.txt
+        echo "$FIRST_COMMIT_BODY" >> .changelog/$PR_NUMBER.txt
+        echo "backticks" >> .changelog/$PR_NUMBER.txt
+        sed -i 's/backticks/```/g' .changelog/$PR_NUMBER.txt
+    - name: Commit and Push
+      env:
+        GIT_USER: ${{ secrets.GIT_USER }}
+        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
+      run: |
+        git branch
+        echo "---"
+        git log -1
+        echo "---"
+        git config --local user.email "dependabot[bot]@users.noreply.github.com"
+        git config --local user.name "dependabot[bot]"
+        git add .changelog
+        git commit --amend --no-edit
+        echo "---"
+        git log -1
+        git push --force "https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}.git" HEAD:${{ github.event.pull_request.head.ref }}
   # checks that a .changelog entry is present for a PR
+  changelog-check-dpbot:
+    runs-on: ubuntu-latest
+    needs: [generate-release-note]
+    steps:
+      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
+        with:
+          # ref: ${{ github.event.pull_request.head.sha }}
+          ref: ${{ github.event.pull_request.head.ref }}
+          fetch-depth: 0 # by default the checkout action doesn't checkout all branches
+      - name: Check for changelog entry in diff
+        run: |
+          # check if there is a diff in the .changelog directory
+          changelog_files=$(git --no-pager diff --name-only HEAD "$(git merge-base HEAD "origin/${{ github.event.pull_request.base.ref }}")" -- .changelog/${{ github.event.pull_request.number }}.txt)
+
+          # If we do not find a file in .changelog/, we fail the check
+          if [ -z "$changelog_files" ]; then
+            # Fail status check when no .changelog entry was found on the PR
+            echo "Did not find a .changelog entry and the 'pr/no-changelog' label was not applied."
+            exit 1
+          else
+            echo "Found .changelog entry in PR!"
+          fi
   changelog-check:
     # If there  a `pr/no-changelog` label we ignore this check
-    if: "!contains(github.event.pull_request.labels.*.name, 'pr/no-changelog') || github.event.pull_request.user.login == 'dependabot'"
+    if: "!contains(github.event.pull_request.labels.*.name, 'pr/no-changelog')"
     runs-on: ubuntu-latest
-
     steps:
-      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
+      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
         with:
-          ref: ${{ github.event.pull_request.head.sha }}
+          # ref: ${{ github.event.pull_request.head.sha }}
+          ref: ${{ github.event.pull_request.head.ref }}
           fetch-depth: 0 # by default the checkout action doesn't checkout all branches
       - name: Check for changelog entry in diff
         run: |
